### ISSUE TITLE
Multiple confidence intervals are not corrected in boot.glmnet

### ISSUE THREAD

**Issue by msmah** [pbreheny/hdrm#3]
Since the data matrix X is usually of multi-dimension, the p-values should be corrected using different methods like Bon Ferroni, etc. So the final confidence intervals in boot.glmnet are not reliable.

**Comment by pbreheny** [comment]
This depends entirely on what you're doing with the confidence intervals. If the user wants to make the intervals wider in order to maintain a family-wise coverage rate, they can do so by specifying `alpha`.
